export const company = {
  "Financial Sector": [
    "HDFC Bank",
    "Bajaj Finance",
    "ICICI Bank",
    "Bajaj Housing",
    "Savani Financials",
  ],
  "Tech Sector": [
    "Affle India",
    "LTI Mindtree",
    "KPIT Tech",
    "Tata Tech",
    "BLS E-Services",
    "Tanla",
  ],
  Consumer: ["Dmart", "Tata Consumer", "Pidilite"],
  Power: ["Tata Power", "KPI Green", "Suzlon", "Gensol"],
  "Pipe Sector": ["Hariom Pipes", "Astral", "Polycab"],
  Others: [
    "Clean Science",
    "Deepak Nitrite",
    "Fine Organic",
    "Gravita",
    "SBI Life",
    "Infy",
    "Happeist Mind",
    "Easemytrip",
  ],
};

export const googleCompanySymbol = {
  "Financial Sector": {
    "HDFC Bank": "HDFCBANK:NSE",
    "Bajaj Finance": "BAJFINANCE:NSE",
    "ICICI Bank": "ICICIBANK:NSE",
    "Bajaj Housing": "BAJAJHFL:NSE",
    "Savani Financials": "511577:BOM",
  },
  "Tech Sector": {
    "Affle India": "AFFLE:NSE",
    "LTI Mindtree": "LTIM:NSE",
    "KPIT Tech": "KPITTECH:NSE",
    "Tata Tech": "TATATECH:NSE",
    "BLS E-Services": "BLSE:NSE",
    Tanla: "TANLA:NSE",
  },
  Consumer: {
    Dmart: "DMART:NSE",
    "Tata Consumer": "TATACONSUM:NSE",
    Pidilite: "PIDILITIND:NSE",
  },
  Power: {
    "Tata Power": "TATAPOWER:NSE",
    "KPI Green": "KPIGREEN:NSE",
    Suzlon: "SUZLON:NSE",
    Gensol: "GENSOL:NSE",
  },
  "Pipe Sector": {
    "Hariom Pipes": "HARIOMPIPE:NSE",
    Astral: "ASTRAL:NSE",
    Polycab: "POLYCAB:NSE",
  },
  Others: {
    "Clean Science": "CLEAN:NSE",
    "Deepak Nitrite": "DEEPAKNTR:NSE",
    "Fine Organic": "FINEORG:NSE",
    Gravita: "GRAVITA:NSE",
    "SBI Life": "SBILIFE:NSE",
    Infy: "INFY:NSE",
    "Happeist Mind": "HAPPSTMNDS:NSE",
    Easemytrip: "EASEMYTRIP:NSE",
  },
};

export const yahooCompanySymbol = {
  "Financial Sector": {
    "HDFC Bank": "HDFCBANK.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Bajaj Housing": "BAJAJHFL.NS",
    "Savani Financials": "SAVFI.BO",
  },
  "Tech Sector": {
    "Affle India": "AFFLE.NS",
    "LTI Mindtree": "LTIM.NS",
    "KPIT Tech": "KPITTECH.NS",
    "Tata Tech": "TATATECH.NS",
    "BLS E-Services": "BLSE.NS",
    Tanla: "TANLA.NS",
  },
  Consumer: {
    Dmart: "DMART.NS",
    "Tata Consumer": "TATACONSUM.NS",
    Pidilite: "PIDILITIND.NS",
  },
  Power: {
    "Tata Power": "TATAPOWER.NS",
    "KPI Green": "KPIGREEN.NS",
    Suzlon: "SUZLON.NS",
    Gensol: "GENSOL.BO",
  },
  "Pipe Sector": {
    "Hariom Pipes": "HARIOMPIPE.NS",
    Astral: "ASTRAL.NS",
    Polycab: "POLYCAB.NS",
  },
  Others: {
    "Clean Science": "CLEAN.NS",
    "Deepak Nitrite": "DEEPAKNTR.NS",
    "Fine Organic": "FINEORG.NS",
    Gravita: "GRAVITA.NS",
    "SBI Life": "SBILIFE.NS",
    Infy: "INFY.NS",
    "Happeist Mind": "HAPPSTMNDS.NS",
    Easemytrip: "EASEMYTRIP.NS",
  },
};

export const initialPortfolioState = {
  "Financial Sector": [
    {
      particulars: "HDFC Bank",
      symbol: "HDFCBANK.NS",
      exchange: "NSE",
      purchasePrice: 1490,
      quantity: 50,
      investment: 74500,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "5",
    },
    {
      particulars: "Bajaj Finance",
      symbol: "BAJFINANCE.NS",
      exchange: "NSE",
      purchasePrice: 6466,
      quantity: 15,
      investment: 96990,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "6",
    },
    {
      particulars: "ICICI Bank",
      symbol: "ICICIBANK.NS",
      exchange: "NSE",
      purchasePrice: 780,
      quantity: 84,
      investment: 65520,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
    {
      particulars: "Bajaj Housing",
      symbol: "BAJAJHFL.NS",
      exchange: "NSE",
      purchasePrice: 130,
      quantity: 504,
      investment: 65520,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
    {
      particulars: "Savani Financials",
      symbol: "SAVFI.BO",
      exchange: "BSE",
      purchasePrice: 24,
      quantity: 1080,
      investment: 25920,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "2",
    },
  ],
  "Tech Sector": [
    {
      particulars: "Affle India",
      symbol: "AFFLE.NS",
      exchange: "NSE",
      purchasePrice: 1151,
      quantity: 50,
      investment: 57550,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
    {
      particulars: "LTI Mindtree",
      symbol: "LTIM.NS",
      exchange: "NSE",
      purchasePrice: 4775,
      quantity: 16,
      investment: 76400,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "5",
    },
    {
      particulars: "KPIT Tech",
      symbol: "KPITTECH.NS",
      exchange: "NSE",
      purchasePrice: 672,
      quantity: 61,
      investment: 40992,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
    {
      particulars: "Tata Tech",
      symbol: "TATATECH.NS",
      exchange: "NSE",
      purchasePrice: 1072,
      quantity: 63,
      investment: 67536,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
    {
      particulars: "BLS E-Services",
      symbol: "BLSE.NS",
      exchange: "NSE",
      purchasePrice: 232,
      quantity: 191,
      investment: 44312,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
    {
      particulars: "Tanla",
      symbol: "TANLA.NS",
      exchange: "NSE",
      purchasePrice: 1134,
      quantity: 45,
      investment: 51030,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
  ],
  Consumer: [
    {
      particulars: "Dmart",
      symbol: "DMART.NS",
      exchange: "NSE",
      purchasePrice: 3777,
      quantity: 27,
      investment: 101979,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "7",
    },
    {
      particulars: "Tata Consumer",
      symbol: "TATACONSUM.NS",
      exchange: "NSE",
      purchasePrice: 845,
      quantity: 90,
      investment: 76050,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "5",
    },
    {
      particulars: "Pidilite",
      symbol: "PIDILITIND.NS",
      exchange: "NSE",
      purchasePrice: 2376,
      quantity: 36,
      investment: 85536,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "6",
    },
  ],
  Power: [
    {
      particulars: "Tata Power",
      symbol: "TATAPOWER.NS",
      exchange: "NSE",
      purchasePrice: 224,
      quantity: 225,
      investment: 50400,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
    {
      particulars: "KPI Green",
      symbol: "KPIGREEN.NS",
      exchange: "NSE",
      purchasePrice: 875,
      quantity: 50,
      investment: 43750,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
    {
      particulars: "Suzlon",
      symbol: "SUZLON.NS",
      exchange: "NSE",
      purchasePrice: 44,
      quantity: 450,
      investment: 19800,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "1",
    },
    {
      particulars: "Gensol",
      symbol: "GENSOL.BO",
      exchange: "BSE",
      purchasePrice: 998,
      quantity: 45,
      investment: 44910,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
  ],
  "Pipe Sector": [
    {
      particulars: "Hariom Pipes",
      symbol: "HARIOMPIPE.NS",
      exchange: "NSE",
      purchasePrice: 580,
      quantity: 60,
      investment: 34800,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "2",
    },
    {
      particulars: "Astral",
      symbol: "ASTRAL.NS",
      exchange: "NSE",
      purchasePrice: 1517,
      quantity: 56,
      investment: 84952,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "6",
    },
    {
      particulars: "Polycab",
      symbol: "POLYCAB.NS",
      exchange: "NSE",
      purchasePrice: 2818,
      quantity: 28,
      investment: 78904,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "5",
    },
  ],
  Others: [
    {
      particulars: "Clean Science",
      symbol: "CLEAN.NS",
      exchange: "NSE",
      purchasePrice: 1610,
      quantity: 32,
      investment: 51520,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "3",
    },
    {
      particulars: "Deepak Nitrite",
      symbol: "DEEPAKNTR.NS",
      exchange: "NSE",
      purchasePrice: 2248,
      quantity: 27,
      investment: 60696,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
    {
      particulars: "Fine Organic",
      symbol: "FINEORG.NS",
      exchange: "NSE",
      purchasePrice: 4284,
      quantity: 16,
      investment: 68544,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
    {
      particulars: "Gravita",
      symbol: "GRAVITA.NS",
      exchange: "NSE",
      purchasePrice: 2037,
      quantity: 8,
      investment: 16296,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "2",
    },
    {
      particulars: "SBI Life",
      symbol: "SBILIFE.NS",
      exchange: "NSE",
      purchasePrice: 1197,
      quantity: 49,
      investment: 58653,
      CMP: 0,
      presentValue: 0,
      gainLoss: 0,
      peRatio: 0,
      latestEarnings: 0,
      portfolioPercent: "4",
    },
  ],
};
